[general]
default_provider = "gemini"
temperature = 0.1
streaming = true
timeout = 30

[openai]
# OpenAI API key - if not set or placeholder, will fall back to OPENAI_API_KEY environment variable
api_key = "your_openai_api_key_here"
model = "gpt-3.5-turbo"
base_url = "https://api.openai.com/v1"
temperature = 0.1
max_tokens = 1000
streaming = true

[gemini]
# Gemini API key - if not set or placeholder, will fall back to GEMINI_API_KEY environment variable
api_key = "your_gemini_api_key_here"
model = "gemini-2.5-pro"
temperature = 0.1
max_tokens = 1000
streaming = true

[claude]
# Anthropic API key - if not set or placeholder, will fall back to ANTHROPIC_API_KEY environment variable
api_key = "your_anthropic_api_key_here"
model = "claude-3-haiku-20240307"
temperature = 0.1
max_tokens = 1000
streaming = true

[pubchem]
base_url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
timeout = 10
max_retries = 3

[web]
port = 8501
host = "localhost"
page_title = "PubChemAgent"
page_icon = "🧪"

[logging]
level = "INFO"
file = ""
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 